#!/usr/bin/bash

if [ ! -d /data/data/com.termux/files/usr/var/cache ];then
	mkdir -p /data/data/com.termux/files/usr/var/cache/
fi
if [ ! -d /data/data/com.termux/files/usr/var/cache/apt ];then
	mkdir -p /data/data/com.termux/files/usr/var/cache/apt/
fi
if [ ! -d data/data/com.termux/files/usr/var/cache/apt/archives ];then
	mkdir -p /data/data/com.termux/files/usr/var/cache/apt/archives/
fi
if [ ! -d data/data/com.termux/files/usr/var/cache/apt/archives/partial ];then
	mkdir -p /data/data/com.termux/files/usr/var/cache/apt/archives/partial/
fi