#!/usr/bin/bash

cd ~/scripts
files=$(find *)
for file in $files ; do
	filedate=$(stat -c %Y ~/scripts/$file)
	extfiledate=$(stat -c %Y ~/termux/scripts/$file)
	if [ $filedate -gt $extfiledate ]; then
		cp ~/scripts/$file ~/termux/scripts/$file
	elif [ $extfiledate -gt $filedate ]; then
		cp ~/termux/scripts/$file ~/scripts/$file
	fi
done
